# docker run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=postgres timescale/timescaledb:2.0.1-pg12



#  docker exec -it timescaledb psql -U postgres

#   GRANT ALL PRIVILEDGES ON DATABASE websitenamehere  to ttm_web_user;